### ISSUE TITLE
Ghost pages - pages exist but not shown in admin menu

### ISSUE THREAD

**Issue by robiso** [wdj-ac/wondercms#4]
If the user visits example.com/newPage and creates some content there which creates the page, this page is not visible in the settings panel menu (its only visible in the database.js and to whomever knows the URL). One of the solutions would be to list all pages from the database for the menu that's visible to the admin in settings to hidden pages.

**Comment by nightillusions** [comment]
I had a similar idea. Perhaps an intermediate table would make sense. You can assign a specific page by drop-down to the menu item.
But that only makes sense in a future version and we first solve this problem by creating an invisible menu item that links to the new page.

**Comment by robiso** [comment]
That indeed only makes sense for the future.

On a side note, would it be possible to do something like explained below + your existing functionality.

1. Check for/read all ->pages in database.js each time a new page is created.
2. List them with a for each loop.
3. Within the for each loop, include your functionality to show/hide for each menu item // something similar to what you already have.

This way, the menu always shows all the pages from database.js and it's practically impossible to make a ghost page.

**Comment by nightillusions** [comment]
Yes, of course thats one way to do it. 
I tried another way here: 41e166c85f1b3525d5c2bdef0d60ea80736e6222

Maybe tomorrow I will have a look at the new code and test your approach.

**Comment by robiso** [comment]
Thanks for taking this into consideration. Testing out your new index.php and will report back.

_Unrelated to this topic
Note: we've released WonderCMS 2.0.3 with a couple small changes noted here: https://github.com/robiso/wondercms/commit/9b868863234fa60695d8ccd5f8878dbdf4ffd12b
To recap: changed version number, CSRF token generator for logging in, 404 header fix, spans to divs
None of these changes make an impact on anything we're talking about on this topic._

**Comment by robiso** [comment]
After a couple of tests, reporting back to say ghost pages still occur. Love your code clean up.

Scenario that takes another page refresh:
 1. Trying to change the visibility of Home by clicking the green "eye".
 2. The page refreshes itself.
 3. Home is still visible in the menu.
 4. Another refresh fixes this.
To be honest, I don't have a clue yet as to why this occurs.

Another possible solution to ghost pages:
1. Each time a new page is created, automatically add it to the menu list.

Let me know what you think.

**Comment by nightillusions** [comment]
> Note: we've released WonderCMS 2.0.3 with a couple small changes noted here: robiso@9b86886

I´ve merged it into my fork master. Will pull it today into this branch. 

> After a couple of tests, reporting back to say ghost pages still occur.

You´re right, I have not fixed it with the latest commit ^^. It was just a pre release with a stand alone function. Today I will solve the issue with ghost pages.

>  To be honest, I don't have a clue yet as to why this occurs.

I found the "faulty" code in my JavaScript part. When I minified the code, the timeout was lost. It´s just because the reload occurs to early. Maybe a clean callback is better then this timeout. 

> Each time a new page is created, automatically add it to the menu list.

This is the solution I will try next 👍

**Comment by robiso** [comment]
> You´re right, I have not fixed it with the latest commit ^^. It was just a pre release with a stand alone function. Today I will solve the issue with ghost pages.

Sorry about this one.

> I found the "faulty" code in my JavaScript part. When I minified the code, the timeout was lost. It´s just because the reload occurs to early. Maybe a clean callback is better then this timeout.

Awesome, I'm not sure in the latter, do you mean a JavaScript one or a PHP one // no clue.

**Comment by nightillusions** [comment]
Everything seems now to be fixed. I even merged the version 2.0.3. https://github.com/wdj-ac/wondercms/tree/url_handling

> Awesome, I'm not sure in the latter, do you mean a JavaScript one or a PHP one // no clue.

In my javascript code I used a timeout to reload the window  after some milliseconds to avoid the hide/show "bug". But when I had minified the code, I had probably forgotten to put it back. 
Before minify:
```
setTimeout(function() {
            window.location.reload()
        }, 500)
```
after:
`c=(setTimeout(function(){window.location.reload()},500),a.attr("data-menu"));`

Please give it a try.

**Comment by robiso** [comment]
I will give this a try in a couple of hours when I get home. Will report back soon. Can't wait!

**Comment by robiso** [comment]
Reporting back.

I had no more issues with having to refresh the page any more. Adding new page automatically to the menu also worked great.

I've however encountered what can be called unwanted behaviour when I tried to reorder the pages by copy pasting home to the bottom of the menu for example, but the page I'm copying gets deleted once you leave an empty menu field. Checked the database and the page gets deleted, but in the menu items in the database, the "no name" pages exist:
```
        "menuItems": {
            "0": {
                "name": "a",
                "slug": "a",
                "visibility": "show"
            },
            "1": {
                "name": "",
                "slug": "",
                "visibility": "show"
            },
            "2": {
                "name": "",
                "slug": "",
                "visibility": "show"
            },
            "3": {
                "name": "home",
                "slug": "home",
                "visibility": "hide"
            },
            "4": {
                "name": "aaa",
                "slug": "aaa",
                "visibility": "hide"
            }
        }
```
while this is in the pages section
```
    "pages": {
        "a": {
            "title": "a",
            "keywords": "Keywords, are, good, for, search, engines",
            "description": "A short description is also good."
        },
        "aaa": {
            "title": "Aaa",
            "keywords": "Keywords, are, good, for, search, engines",
            "description": "A short description is also good.",
            "content": "<h2>Click here to create some content<\/h2><p>Once you do that, this page will be eventually visited by search engines.<\/p>"
        }
    },
```
Not exactly sure on what should happen when the menu field is empty. What do you think, should the empty menu field be populated at the bottom of the menu (so in cases when someone wants to change the order of the pages)? Should each page that's in pages param (and maybe menuItems param) in the db be repopulated each time some other action happens?

Also checking out your update system :+1:

**Comment by nightillusions** [comment]
last but not least, give this a try a89a03b6a3248bdb44387a9f244ff23a365617dc
:)

**Comment by robiso** [comment]
The whole menu system is absolutely beautiful, along with the page ordering - love it!
Everything was working flawlessly until it hit a stop, as shown below (cannot add any more pages.)

![cannot-add-new-pages-on-this-setup](https://cloud.githubusercontent.com/assets/6200139/25487730/5c9940b4-2b65-11e7-8f12-862d3a9cb148.png)
On this setup, adding new pages is impossible. Clicking the + only refreshes the page without adding any new items.

Trying to re-create the problem:
 1. Add new page item.
 2. Add another new page item.
 3. Change visibility of last item.
 4. Adding new items doesn't work anymore at this stage until:
 - you delete an item, creating a page is again possible, just not after changing the visibility of it and then trying to add a new one. I'm not exactly sure as to why this happens yet and I'm still trying to figure out when this happens, as the steps that cause this aren't exactly consistent as I tried to replicate above.

--
I additionally noticed a CSS issue (page scrolls left and right in settings, the scrollbar can be seen at the bottom of the screenshot), this seems trivial and I'll try to push a fix soon.

I'd also like to thank you again for trying to crack this nut!

**Comment by robiso** [comment]
After a couple of more resets and tests, I'm unable to reproduce the problem I mentioned in the earlier post. Can anyone else give this a try please?

**Comment by nightillusions** [comment]
Steps to produce:
1. Create two new menu items
2. Delete the first one
3. Adding new menu item fails

The Problem here is, that I check all menu items slug in order to prevent overwriting an existing page by a new menu item with same slug:
`foreach($db->config->{$field} as $key=>$value)if($value->slug == $slug)return;`

If I change this check to something like below, it works but it doesn't feel right:
`foreach($db->config->{$field} as $key=>$value)if($value->slug == $slug)$slug.="-new";`

database.js:
```
"2": {
                "name": "New menu item",
                "slug": "new-menu-item-3",
                "visibility": "hide"
            },
            "3": {
                "name": "New menu item",
                "slug": "new-menu-item-3-new",
                "visibility": "hide"
            }
```

Here is the commit: https://github.com/wdj-ac/wondercms/commit/a2f785d14a123d945c22cb62693743b6588d1299

Take a look at my install. There is no CSS issue: http://wondercms.jordin.eu/

**Comment by robiso** [comment]
If that's the only step that this happens, do you think we need to fix it?

On your website:  http://wondercms.jordin.eu/ I have the same CSS problem (scrolling left right when the settings panel is open). I think this has something to do because your rows and container is wrapper in a couple of col-xs's. This probably affects only specific browsers, I'm on Firefox I'll check out in a couple of hours and try to provide a fix or solve it somehow else.

Let me know if you think the above $slug.="-new"; really needs fixing or should we just leave it out because it's such a specific case?

**Comment by robiso** [comment]
Here's the latest WonderCMS 2.0.6 with your menu functionality included and without the hook priority functionality.
The index.php below is provided with some fixes:
 - code consistency, spaces to tabs
 - fixed small bug on wrong function name call on line 266 (the bug was -> newMenuTItems)
 - changed container to container-fluid to avoid margin and padding in some browsers

**Like mentioned, below is the latest 2.0.6 version with your fully working menu functionality and fixes**. I think you've done a wonderful job, all we need to do is test it some more before releasing it. Drive it for a spin and thank you for making this possible @wdj-ac 

[index.php.zip](https://github.com/wdj-ac/wondercms/files/964388/index.php.zip)

Kindly asking for some testing in different environments.
I will report back if anything specific is bug worthy :grin: 

EDIT: Reuploaded zip with added setlocale, this fixes my problem of converting šok to ok, with setlocale it converts correctly to sok.

**Comment by robiso** [comment]
Sometimes I still run into this issue where I can't create a new page.
This also showed up in my error log :
`PHP Warning:  Creating default object from empty value in index.php on line 121`
Line 121 is: `case 4: $db->{$args[0]}->{$args[1]}->{$args[2]} = $args[3]; break;` from the index attached above.

**Comment by nightillusions** [comment]
Thank you for saving me the work of the migration :)
I moved setlocale() to the top and removed the error operator. This should be the optimal solution.

`Sometimes I still run into this issue where I can't create a new page.`
I was not able to reproduce this issue, but while analyzing the code, the _ slugify() function could return an empty string if all the letters are special character.

`PHP Warning: Creating default object from empty value in index.php on line 121`
This indicates, that $args[3] was set but empty. I am not able to find any scenario where this could happen. Maybe the slugify fix helps. 

I will create some environments and test it

New Commit: 93f11490ebcee75dea0e66636889234d24809c10

**Comment by nightillusions** [comment]
@robiso I´ve found an core bug in the `_saveAction()` function when `$target` is set to `'config'`. 

Steps to repuduce:
1. Edit Login URL & press enter
2. Click outside textarea

Now there is a `<br>` saved in database behind the loginURL:
```
"config": {
    ...
    "login": "loginURL<br>",
```

Maybe you could implement the slugify function `$content = _slugify($content);` , but this will always return lower letters.
An other solution is to bringing back the old way: `$content = array_filter(array_map('trim', explode('<br>', $content)));`

Adding here: 
`if ($target === 'config'){ $content = XXX; wCMS::set('config',$fieldname,$content);}`

What do you think?

------------------------

[Edit:]
- tested on fresh install LAMP Server
- tested on fresh install LEMP Server

**Comment by robiso** [comment]
@wdj-ac you're most welcome. Thank you for the fix on empty string. I could not reproduce the 'not being able to add new pages', but I think this happened when two pages with the "-extra" param were made in a row. I ran into a new issue, which I'll explain in a new issue to be consistent.

// offtopic
What you're mentioning regarding to the trim function can be seen in the parseURL function
```
	public static function parseUrl() {
		if ($_GET['page'] == wCMS::get('config','login')) return htmlentities($_GET['page'], ENT_QUOTES, 'UTF-8'); // here we return the login param without trimming it and without lower casing it, to enable users to have this case sensitive
		return isset($_GET['page']) ? trim(htmlentities(mb_strtolower($_GET['page']), ENT_QUOTES, 'UTF-8'), '/') : '';
	}
```

Do you think it would make more sense to also trim the login URL? Note: we still want the user to have this part (loginURL) case sensitive. I'm not really bothered by the fact an enter is possible - the cleanest solution if you guys agree would be to add trimming to the loginURL, if it's really necessary.

**Comment by nightillusions** [comment]
@robiso The "-extra" param will append to slug string. When there is already a `new-page-1-extra` then it becomes  `new-page-1-extra-extra`. Not a beauty, but still works ^^.

// offtopic
I think case sensitive is okay. Just check that there is no `<br>`, because it breaks the login url.
